### PR TITLE
Add ICD10-pcs

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Needs to have a copyright statement

**Comment by jmandel** [comment]
Isn't that an upstream issue? The shell of this resource came directly from https://terminology.hl7.org/5.3.0/CodeSystem-icd10PCS.html

**Comment by grahamegrieve** [comment]
once content is included, I care more about the copyright statement

**Comment by jmandel** [comment]
OK! Just here in this PR, or upstream?

**Comment by grahamegrieve** [comment]
just in this PR, and I'll ask TI what their policy is

**Comment by jmandel** [comment]
I added a note.

**Comment by grahamegrieve** [comment]
@jmandel can you fix this: "content": "not-present"

**Comment by reubendaniels** [comment]
Hi Josh

Back in March 2023 the HTA subcommittee of the TSMG updated the following Confluence page for ICD10-PCS in consultation with CMS: https://confluence.hl7.org/display/TA/ICD-10+Procedure+Coding+System

You should be able to reuse the text provided in _IP Information and Licensing Information_ here.

Separately, I will ensure the metadata record in THO is appropriately updated as well.

Cheers

**Comment by jmandel** [comment]
Thanks @grahamegrieve  and @reubendaniels  -- I've made these updates.

**Pull request merged**
