### PR TITLE
adding RadLex CodeSystem for inclusion in tx.fhir.org

### PR DESCRIPTION
**Pull request by david-simons**
In response to: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Warning.20message.20when.20using.20Radlex.20codes/near/273009347 @grahamegrieve 

image

### CODE REVIEW

**Comment by david-simons** [comment]
Based on http://radlex.org/ download (Radlex.xls), without Adaptations - only structural conversion to a FHIR CodeSystem resource - aimed at respecting the RadLex Terms of Use.

Validates using Firely terminal.

Note: We have not yet included synonyms.

**Comment by david-simons** [comment]
Based on http://radlex.org/ download (Radlex.xls), without Adaptations other than structural conversion to a FHIR CodeSystem resource.

Validates using Firely terminal.

Note: We have not yet included synonyms.

**Comment by david-simons** [comment]
Maybe good to involve RSNA radlex.org on this PR - Ideally they host this on radlex.org.

**Comment by david-simons** [comment]
@grahamegrieve 

My colleague @oijauregui was so kind to also add the Python script he wrote for transforming the RadLex.xls into a FHIR CodeSystem-radlex.json.

With help of another colleague, I am reaching out to RSNA/RadLex team to check their interest in publishing at their source.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
